stages:
  baseline:
    cmd: export LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64 && export PYTHONPATH=$PWD
      && python3 tools/main.py --work_dir=artifacts/baseline --backbone=B6 --dropout_rate=0.1
      --lr_max=5 --lr_exp_decay=0.5 --focal_loss_gamma=4 --focal_loss_alpha=0.8 --hair_prob=0.01
      --microscope_prob=0.01 --lr_warm_up_epochs=5 --image_height=384 --batch_size=400
      --stage=baseline
    deps:
    - augmentations
    - config
    - data
    - dataset
    - debug_tools
    - model
    - submission
    - tools
    outs:
    - artifacts/baseline
    metrics:
    - metrics/metrics.txt:
        cache: false
  b0:
    cmd: export LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64 && export PYTHONPATH=$PWD
      && python3 tools/main.py --work_dir=artifacts/b0
      --backbone=B0 --dropout_rate=0.1 --lr_max=1 --lr_exp_decay=0.5 --focal_loss_gamma=4
      --focal_loss_alpha=0.8 --hair_prob=0.1 --microscope_prob=0.01 --lr_warm_up_epochs=5
      --image_height=256 --batch_size=128 --stage=b0 --save_best_n=3
    deps:
    - augmentations
    - config
    - data
    - dataset
    - debug_tools
    - model
    - submission
    - tools
    outs:
    - artifacts/b0
    metrics:
    - metrics/metrics_b0.txt:
        cache: false
  resnet50:
    cmd: export LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64 && export PYTHONPATH=$PWD
      && python3 tools/main.py --work_dir=artifacts/resnet101
      --backbone=ResNet50 --dropout_rate=0.1 --lr_max=1 --lr_exp_decay=0.7 --focal_loss_gamma=4
      --focal_loss_alpha=0.8 --hair_prob=0.1 --microscope_prob=0.01 --lr_warm_up_epochs=5
      --image_height=384 --batch_size=128 --stage=resnet50 --save_best_n=3 --epochs_full=20
    deps:
      - augmentations
      - config
      - data
      - dataset
      - debug_tools
      - model
      - submission
      - tools
    outs:
      - artifacts/resnet50
    metrics:
      - metrics/metrics_resnet50.txt:
          cache: false
  b5:
    cmd: export LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64 && export PYTHONPATH=$PWD
      && python3 tools/main.py --work_dir=artifacts/b5
      --backbone=B5 --dropout_rate=0 --lr_max=5 --lr_exp_decay=0.8 --focal_loss_gamma=4
      --focal_loss_alpha=0.8 --hair_prob=0 --microscope_prob=0 --lr_warm_up_epochs=5
      --image_height=512 --batch_size=128 --stage=b5 --save_best_n=3 --cut_mix_prob=0.05 --cut_out_prob=0
      --epochs_full=12 --use_meta=0 --val_ttas=1
    deps:
    - augmentations
    - config
    - data
    - dataset
    - debug_tools
    - model
    - submission
    - tools
    outs:
    - artifacts/b5
    metrics:
    - metrics/metrics_b5.txt:
        cache: false
