stages:
  baseline:
    cmd: export LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64 && export PYTHONPATH=$PWD
      && python3 tools/main.py --work_dir=artifacts/baseline --backbone=B6 --dropout_rate=0.1
      --lr_max=5 --lr_exp_decay=0.5 --focal_loss_gamma=4 --focal_loss_alpha=0.8 --hair_prob=0.01
      --microscope_prob=0.01 --lr_warm_up_epochs=5 --image_height=384 --batch_size=400
      --stage=baseline
    deps:
    - augmentations
    - config
    - data
    - dataset
    - debug_tools
    - model
    - submission
    - tools
    outs:
    - artifacts/baseline
    metrics:
    - metrics/metrics.txt:
        cache: false
  b0:
    cmd: export LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64 && export PYTHONPATH=$PWD
      && python3 tools/main.py --work_dir=artifacts/b0
      --backbone=B0 --dropout_rate=0.01 --lr_max=10 --lr_exp_decay=0.5 --focal_loss_gamma=4
      --focal_loss_alpha=0.8 --hair_prob=0.1 --microscope_prob=0.01 --lr_warm_up_epochs=5
      --image_height=256 --batch_size=256 --stage=b0 --save_best_n=3
    deps:
    - augmentations
    - config
    - data
    - dataset
    - debug_tools
    - model
    - submission
    - tools
    outs:
    - artifacts/b0
    metrics:
    - metrics/metrics_b0.txt:
        cache: false
