stages:
  baseline:
    cmd: export LD_LIBRARY_PATH=/usr/local/cuda-11/lib64 && export CUDA_DIR=/usr/local/cuda-11 && export XLA_FLAGS="--xla_gpu_cuda_data_dir=/usr/local/cuda-11" && export TF_XLA_FLAGS="--tf_xla_enable_xla_devices --tf_xla_cpu_global_jit" && export PYTHONPATH=$PWD
      && python3 tools/main.py --work_dir=artifacts/baseline
      --backbone=B0 --dropout_rate=0.1 --lr_max=5 --lr_exp_decay=0.5 --focal_loss_gamma=4
      --focal_loss_alpha=0.8 --hair_prob=0.01 --microscope_prob=0.01 --lr_warm_up_epochs=5
      --image_height=256
    deps:
    - augmentations
    - config
    - data
    - dataset
    - debug_tools
    - model
    - submission
    - tools
    outs:
    - artifacts/baseline
    metrics:
    - metrics/metrics.txt:
        cache: false
